//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be less than 1.
        /// </summary>
        internal static string Can_Not_Be_Zero {
            get {
                return ResourceManager.GetString("Can_Not_Be_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during resource creation..
        /// </summary>
        internal static string Erro_Creation {
            get {
                return ResourceManager.GetString("Erro_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory produced a null item..
        /// </summary>
        internal static string Factory_Produced_Null_Item {
            get {
                return ResourceManager.GetString("Factory_Produced_Null_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new resource..
        /// </summary>
        internal static string Failed_Create_Resource {
            get {
                return ResourceManager.GetString("Failed_Create_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Increment must be lower than max - init.
        /// </summary>
        internal static string Max_Create_Increament {
            get {
                return ResourceManager.GetString("Max_Create_Increament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max pool size must be greater than zero..
        /// </summary>
        internal static string Max_pool_Size_Min_Value {
            get {
                return ResourceManager.GetString("Max_pool_Size_Min_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pool size must be greater than or equal to the initial pool size.
        /// </summary>
        internal static string Max_Pool_Size_More_Than_Init {
            get {
                return ResourceManager.GetString("Max_Pool_Size_More_Than_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink interval must be at least 30 minutes.
        /// </summary>
        internal static string Min_Shrink_Interval {
            get {
                return ResourceManager.GetString("Min_Shrink_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object can not be null.
        /// </summary>
        internal static string Object_Can_Not_Be_Null {
            get {
                return ResourceManager.GetString("Object_Can_Not_Be_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool size exceeded maximum capacity..
        /// </summary>
        internal static string Poo_Maximum_Capacity {
            get {
                return ResourceManager.GetString("Poo_Maximum_Capacity", resourceCulture);
            }
        }
    }
}
